# Gems
plugins:
   - jekyll-paginate
paginate: 10

# user variables, change this to make custom site.


name: powerprove
desc: Yet another simple theme for Jekyll.
author:
  name: neizod
  avatar: /images/avatar.png
  profile: null2root
  socials:
    facebook:
    twitter: //twitter.com/powerprov3
    google-plus:
    github: //github.com/powerprove
    stack-overflow:
    instagram:
    pinterest:
    steam:
license: MIT License neizod,


# theme variables, change this to make site looks best.
baseurl:
paginate: 10


# system variables, do not change unless you knew what's it does.
paginate_path: page/:num
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
